api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "tip-transform"
type = "function"
uid = "9f6ecbe7-fda3-57a0-155c-409e3bd1e7f23794277a"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
